// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEm43RKIQ0EBF1jn_gE32zANSZPzIKSAE',
    appId: '1:330201716515:web:dc6309003ce146cb925e96',
    messagingSenderId: '330201716515',
    projectId: 'hoodie-bc4c2',
    authDomain: 'hoodie-bc4c2.firebaseapp.com',
    databaseURL: 'https://hoodie-bc4c2-default-rtdb.firebaseio.com',
    storageBucket: 'hoodie-bc4c2.appspot.com',
    measurementId: 'G-6GQ9YVQBLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHPu4VFkGFFc1N9ZRZFkB7ShA6cuWQJU',
    appId: '1:330201716515:android:a2264afe8ece11c0925e96',
    messagingSenderId: '330201716515',
    projectId: 'hoodie-bc4c2',
    databaseURL: 'https://hoodie-bc4c2-default-rtdb.firebaseio.com',
    storageBucket: 'hoodie-bc4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPKOXckfedebVpLI5zCvUnCkKrkWh_JI',
    appId: '1:330201716515:ios:934e8c6512444b00925e96',
    messagingSenderId: '330201716515',
    projectId: 'hoodie-bc4c2',
    databaseURL: 'https://hoodie-bc4c2-default-rtdb.firebaseio.com',
    storageBucket: 'hoodie-bc4c2.appspot.com',
    androidClientId: '330201716515-vv0hi53b57sj96i3b83ai0juuhdm1226.apps.googleusercontent.com',
    iosClientId: '330201716515-8vbu6smr3dgoj8f4pkvqfl09fe23di9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoodie',
  );
}
